### ISSUE TITLE
Allow use of a fallback/default value for `MPITRAMPOLINE_MPIEXEC`

### ISSUE THREAD

**Issue by ocaisa** [eschnett/MPItrampoline#12]
It's possible to configure a default MPI library with `-DMPITRAMPOLINE_DEFAULT_LIB=XXX`, it would be good to be able to also configure a default mpiexec (`-DMPITRAMPOLINE_DEFAULT_MPIEXEC=XXX`) so that one can have a fully functional fallback in place at build time.

**Comment by ocaisa** [comment]
BTW it was your idea in https://github.com/easybuilders/easybuild-easyconfigs/pull/14607#issuecomment-999104775, I was just moving it over here!

**Comment by eschnett** [comment]
Done.
