### ISSUE TITLE
Supporting `MPIX_Query_cuda_support()`

### ISSUE THREAD

**Issue by ocaisa** [eschnett/MPItrampoline#16]
While not part of the standard, `MPIX_Query_cuda_support()` is available in a number of MPI implementations (see https://github.com/pmodels/mpich/pull/4741). It's also being used by a number of applications (and hopefully that will grow, see my issue at https://github.com/lammps/lammps/issues/3140 which links back to the support in GROMACS). This would be a valuable inclusion in MPItrampoline since it would then be able to handle the runtime detection of CUDA support in the MPI implementation.

**Comment by ocaisa** [comment]
This is also an issue for MPIwrapper as to find the function in Open MPI you need to use `mpi-ext.h`

**Comment by eschnett** [comment]
Are you aware of a cmake module to auto-detect whether `mpi-ext.h` exists, and if so, whether `MPIX_Query_cuda_support` and friends exist? It seems there are MPI implementations which don't support this, and MPIwrapper will need to detect at compile time whether this feature is present.

MPItrampoline can obviously only offer run-time detection.

**Comment by ocaisa** [comment]
Even just to be able to set the return value for that function via a CMake option  to MPIwrapper would be enough for a first implementation (with a default return value of false)

**Comment by eschnett** [comment]
See https://github.com/eschnett/MPIwrapper/pull/4. Currently waiting for an error in Github actions to resolve itself.

**Comment by eschnett** [comment]
Done.
