### ISSUE TITLE
Add support for MPI profiling interface

### ISSUE THREAD

**Issue by ocaisa** [eschnett/MPItrampoline#21]
Each standard MPI function can be called with an `MPI_` or `PMPI_` prefix (quoting from https://www.open-mpi.org/faq/?category=perftools#PMPI), I _think_ MPItrampoline doesn't currently support the `PMPI_` calls.

**Comment by ocaisa** [comment]
These calls are used by profiling tools like [Scalasca](https://www.scalasca.org/)

**Comment by ocaisa** [comment]
Another important comment there:

> Be sure you make the library dynamic. A static library can experience the linker problems described in the Complications section of the Profiling Interface chapter of the MPI standard.

which I guess will lead back to the OSX issues mentioned in #13

**Comment by eschnett** [comment]
Yes, the profiling interfaces are not yet implemented. I am only vaguely familiar with them, I will have to study the standard.

I guess the complications described there have to do with resolving symbols at run time, i.e. what ELF calls "semantic interposition".

**Comment by eschnett** [comment]
See https://github.com/eschnett/MPItrampoline/pull/22. Do you have time to test this?

**Comment by ocaisa** [comment]
I can build [Score-P](https://www.vi-hps.org/projects/score-p/) later today, that should be a good test

**Comment by ocaisa** [comment]
BTW I did do the build of Score-P and successfully used it, so I think this can be closed
